#ifndef L2_DXF2GERBER_GLOBAL_H
#define L2_DXF2GERBER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(L2_DXF2GERBER_LIBRARY)
#  define L2_DXF2GERBERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define L2_DXF2GERBERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // L2_DXF2GERBER_GLOBAL_H
