#ifndef L2_DXF2ODB_GLOBAL_H
#define L2_DXF2ODB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(L2_DXF2ODB_LIBRARY)
#  define L2_DXF2ODBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define L2_DXF2ODBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // L2_DXF2ODB_GLOBAL_H
